version: '3'

services:

  db:
    image: mysql:latest
    container_name: webapp8_bbdd
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=webapp8_bbdd
      - MYSQL_ROOT_PASSWORD=DawWebApp8

  web:
    build: .
    image: marcoszas/webapp8:latest
    ports:
      - "8443:8443"
    container_name: webapp8
    restart: always
    links:
      - "db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/webapp8_bbdd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=DawWebApp8
